-- cliente definition

-- Drop table

-- DROP TABLE cliente;

CREATE TABLE cliente (
                                id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                data_cadastro timestamp NULL,
                                cpf varchar(255) NULL,
                                nome varchar(255) NULL,
                                email varchar(255) NULL,
                                CONSTRAINT pk_cliente PRIMARY KEY (id)
);


-- produto definition

-- Drop table

-- DROP TABLE produto;

CREATE TABLE produto (
                                id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                data_cadastro timestamp NULL,
                                nome varchar(255) NULL,
                                descricao varchar(500) NULL,
                                preco numeric NULL,
                                categoria varchar(255) NULL,
                                imagem varchar(255) NULL,
                                CONSTRAINT pk_produto PRIMARY KEY (id)
);